name: daily
on:
  workflow_dispatch:
  schedule:
    - cron: '42 0 * * *' # daily at 00:42
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: AUTOBAHN=1 ./ci/test.sh
      - uses: actions/upload-artifact@v3
        with:
          name: coverage.html
          path: ./ci/out/coverage.html
